### ISSUE TITLE
the question about the loss function

### ISSUE THREAD

**Issue by Yu-Cheung** [meteorshowers/StereoNet-ActiveStereoNet#53]
Hi， @meteorshowers ！
Thanks for your work, it's useful for me. When I read the code, I find that in `train_ent_disp.py` you import `My_loss` from the `disparity.models.loss` module, but I don't find this function.

**Comment by z-x-j** [comment]
请问解决了吗？

**Comment by zcy5417** [comment]
已收到！祝每天开开心心！！

**Comment by GEM26-Jay** [comment]
> 已收到！祝每天开开心心！！

你收到损失函数源码了吗?

**Comment by zcy5417** [comment]
已收到！祝每天开开心心！！

**Comment by AI-student-wl** [comment]
你好，你的工作对我非常有用，能告诉我你的损失函数源码吗，感谢

**Comment by zxcv666789** [comment]
你好 请问你解决了吗 可以交流一下吗！ 谢谢！

**Comment by zcy5417** [comment]
已收到！祝每天开开心心！！

**Comment by XinyingZheng** [comment]
> 已收到！祝每天开开心心！！

老哥，能给我转发一份么，非常感谢，这个stereonet的复现，没有损失函数。。
